# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure(2) do |config|
  config.vm.synced_folder "./data", "/opt"
	
  config.vm.define "db" do |db|
    db.vm.box = "atorre/daw"
    db.vm.network "private_network", ip: "192.168.100.100"
    
	db.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--memory", "500"]
	end
    
    db.vm.provision "shell" do |s|
	  s.path = "dbProvision.sh"
  	end
  end
   
  
  config.vm.define "web" do |web|
    web.vm.box = "atorre/daw"
    web.vm.network "private_network", ip: "192.168.100.200"
    
	web.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--memory", "500"]
	end
    
    web.vm.provision "shell" do |s|
	  s.path = "webProvision.sh"
  	end
  end
end
